[package]
name = "gadget-metrics"
version = "0.1.0"
description = "Metrics metapackage for Tangle Blueprints"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
gadget-rpc-calls = { workspace = true, optional = true }

[features]
default = ["rpc-calls"]
rpc-calls = ["gadget-rpc-calls"]
