[package]
name = "blueprint-router"
version = "0.1.0"
edition.workspace = true

[dependencies]
blueprint-core.workspace = true
bytes.workspace = true
document-features = { workspace = true }
pin-project-lite.workspace = true
tower.workspace = true
hashbrown = { workspace = true, default-features = false, features = ["default-hasher", "inline-more"] }
futures = { workspace = true, features = ["alloc"] }

[dev-dependencies]
blueprint-sdk = { workspace = true, features = ["macros"]}
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tower = { workspace = true, features = ["util", "timeout", "limit", "load-shed", "steer", "filter"] }

[features]
default = ["tracing"]

#! `blueprint-router` is fully `no_std` compatible

#! ### Core

## Enable [tracing] support
##
## [tracing]: https://crates.io/crates/tracing
tracing = ["blueprint-core/tracing"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
