[package]
name = "gadget-crypto-sp-core"
version = "0.1.0"
edition = "2021"

[dependencies]
gadget-std = { workspace = true }
gadget-crypto-core = { workspace = true, features = ["tangle"] }
sp-core = { workspace = true, features = ["full_crypto"] }
hex = { workspace = true, features = ["alloc"] }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }
thiserror = { workspace = true }

[dev-dependencies]
gadget-crypto-sp-core = { path = ".", features = ["std", "bls"] }

[features]
default = ["std"]
std = [
    "gadget-crypto-core/std",
    "gadget-std/std",
    "serde/std",
    "serde_json/std",
    "sp-core/std",
] 
bls = ["sp-core/bls-experimental"]