[package]
name = "zk-gadget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-rustls = { workspace = true }
mpc-net = { workspace = true }
webb-gadget = { workspace = true }
gadget-core = { workspace = true }
bincode2 = { workspace = true }
tokio = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true, features = ["derive"] }
async-trait = { workspace = true }
parking_lot = { workspace = true }
log = { workspace = true }
hex = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
tonic = "0.10.2"
prost = "0.12.1"
sp-runtime = { workspace = true }
sc-utils = { workspace = true }
sc-client-api = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
rcgen = "0.11.3"
parity-scale-codec = { workspace = true }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[build-dependencies]
tonic-build = "0.10.2"