[package]
name = "dfns-cggmp21-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "net"] }
gadget-common = { workspace = true }
gadget-core = { workspace = true }
protocol-macros = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
dfns-cggmp21 = { workspace = true, features = ["all-curves"] }
round-based-21 = { workspace = true }
curv = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
bincode2 = { workspace = true }
digest = { workspace = true }

sp-core = { workspace = true, features = ["std"] }
sp-io = { workspace = true, features = ["std"] }

frame-support = { workspace = true  }
parity-scale-codec = { workspace = true }

serde = { version = "1.0.193", features = ["derive"] }
rand = { workspace = true }
rand_chacha = { workspace = true }
hex = { workspace = true }
test-utils = { workspace = true }
parking_lot = { workspace = true }
sha2 = { workspace = true }
