[template]
cargo_generate_version = ">=0.17.4"
ignore = [".git", "blueprint.json", "blueprint.lock"]


[placeholders.gh-username]
type = "string"
prompt = "Your GitHub username (or organization)"
# The username cannot end with a hyphen, too, but
# this requirement is not captured by the regex at the moment.
regex = "^[A-Za-z0-9][A-Za-z0-9-]{0,38}$"

[placeholders.project-description]
type = "string"
prompt = "A short description"

[placeholders.project-homepage]
type = "string"
prompt = "Your project homepage"

[placeholders.flakes]
type = "bool"
prompt = "Do you want to use Nix & Nix Flakes?"
default = false

[conditional.'!flakes']
ignore = [ "flake.nix", "flake.lock", ".envrc" ]
