[env]
# Temporary hack for Tangle blueprints to get the workspace root
#
# See: https://github.com/rust-lang/cargo/issues/3946#issuecomment-973132993
CARGO_WORKSPACE_DIR = { value = "", relative = true }
