[package]
name = "ecdsa-threshold-mpc"
version = "0.1.0"
edition = "2021"
description = "A threshold MPC blueprint allowing key generation, threshold signing, and key refreshes."
authors = ["drewstone <drewstone329@gmail.com>"]
license = "Unlicense"
homepage = "https://tangle.tools"
repository = "https://github.com/webb-tools/ecdsa-threshold-mpc"
readme = "README.md"
categories = ["cryptography", "cryptography::cryptocurrencies", "tangle-blueprint"]
keywords = ["tangle", "blueprint", "avs"]
rust-version = "1.79"

[dependencies]
tracing = { workspace = true }
async-trait = { workspace = true }
gadget-sdk = { workspace = true, features = ["std"] }
gadget-common = { workspace = true, features = ["std"] }

color-eyre = { workspace = true }
tokio = { workspace = true, default-features = false, features = ["full"] }
subxt-signer = { workspace = true, features = ["sr25519", "subxt", "std"] }
tracing-subscriber = { workspace = true, features = ["parking_lot", "env-filter"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sp-core = { workspace = true, features = ["std"] }
itertools = { workspace = true }

cggmp21 = { version = "0.4" }
cggmp21-keygen = { version = "0.3" }
key-share = { version = "0.4", default-features = false }

generic-ec = { version = "0.4.1", default-features = false } 
generic-ec-zkp = { version = "0.4.1", default-features = false } 
round-based = { version = "0.3", default-features = false }
udigest = { version = "0.2.1", default-features = false }
digest = { version = "0.10", default-features = false }
sha2 = { version = "0.10", default-features = false }

[build-dependencies]
blueprint-metadata = "0.1"

[features]
default = ["std"]
std = []
