[package]
name = "gadget-context-derive"
version = "0.3.2"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Procedural macros for deriving Context Extension traits from `gadget-sdk`"

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, default-features = true, features = ["full"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }

[dev-dependencies]
blueprint-sdk = { workspace = true, features = ["std", "macros", "evm", "tangle", "eigenlayer", "testing", "networking", "networking-sp-core-ecdsa", "local-store"] }

async-trait.workspace = true
trybuild = { workspace = true }

# EVM Stuff
alloy-network = { workspace = true }
alloy-provider = { workspace = true }
alloy-transport = { workspace = true }
round-based = { workspace = true, features = ["derive"] }
serde = { workspace = true }
subxt-core.workspace = true

[features]
default = ["std"]
networking = []
std = []

tangle = []
evm = []
