[package]
name = "gadget-crypto-k256"
version = "0.1.0"
edition = "2021"

[dependencies]
gadget-crypto-core = { workspace = true, features = ["k256"] }
gadget-std = { workspace = true }
k256 = { workspace = true, features = ["ecdsa", "alloc"] }
serde = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }
thiserror = { workspace = true }
hex = { workspace = true, features = ["alloc"] }

[features]
default = ["std"]
std = [
    "gadget-crypto-core/std",
    "gadget-std/std",
    "serde/std",
    "serde_json/std",
    "k256/std",
] 