name: Validate PR

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: rust-validation-${{ github.head_ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: full
  RUST_LOG: "gadget=trace"
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-09-28
          components: rustfmt

      - name: Check Formatting
        run: cargo fmt -- --check

  linting:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-09-28
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: Install protobuf
        run: sudo apt-get install protobuf-compiler

      - name: Run Clippy
        run: cargo clippy --tests -- -D warnings

  build:
    timeout-minutes: 120
    name: cargo build
    runs-on: macos-latest
    strategy:
        matrix:
            package: [gadget-core, gadget-common, zk-saas-protocol, dfns-cggmp21-protocol, threshold-bls-protocol]
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-09-28

      - uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: install protobuf
        run: brew install protobuf

      - name: build
        run: cargo build --workspace --package ${{ matrix.package }}

  testing:
    timeout-minutes: 120
    name: cargo test
    runs-on: macos-latest
    strategy:
        matrix:
            package: [gadget-core, gadget-common, zk-saas-protocol, dfns-cggmp21-protocol, threshold-bls-protocol, zcash-frost-protocol]
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-09-28

      - uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: install protobuf
        run: brew install protobuf

      - name: install cargo-nextest
        run: cargo install cargo-nextest --locked

      - name: tests
        if: ${{ matrix.package != 'zk-saas-protocol' }}
        run: cargo nextest run --release --nocapture --package ${{ matrix.package }}

      - name: tests (parallel enabled)
        if: ${{ matrix.package == 'zk-saas-protocol' }}
        run: cargo nextest run --features=parallel --release --nocapture --package ${{ matrix.package }}
